### PR TITLE
[fix] Fix automatic geocoding in extended apps (eg: openwisp-controller) #44

### LINKED ISSUE #44: [ux] Automatically calculate geographic coordinates or address
When the position on the geographic map is updated:

1. if the address field is empty we should automatically get the best address from the geographic coordinates and update the address field with the result
2. if the address field is not empty we should ask the user if the user wants the map to be updated (for now with a simple javascript confirm dialog); If the user replies affirmatively we can do the same described in point 1

When address field is updated:

1. If the geographic coordinates on the map are not set, we can get the geographic coordinates  from the address and update the map accordingly
2 if the geographic coordinates on the map are already set, we should ask the user if the user wants the map to be updated (for now with a simple javascript confirm dialog); If the user replies affirmatively we can do the same described in point 1

For the geocoding operations, we can use [geopy](https://geopy.readthedocs.io/).

We should implement an abstraction that allows to change the provider, trying to support at least Google Maps, Nominatim and ArcGIS in the first version fo this feature.

We should handle failures and retry, retry by default 3 times with a delay of 1 second in case of failures, the geocoding library should have a built-in implementation for this, [see RateLimiter](https://github.com/geopy/geopy/blob/5f8e457b700b59221401726e5983175156b20a0a/geopy/extra/rate_limiter.py#L15).

We will likely need the addition of a few django global settings that allow to set:
- the chosen provider, defaults to `ArcGIS`
- the API key, defaults to `None`
- whether the django app may refuse to start if the testing of the geocoding operation fails, defaults to `True`, eg: `DJANGO_LOCI_STRICT_GEOCODE_TEST`
- amount of retries after failures, default to 3
- delay in seconds before trying again after a failure, default to 1

On startup, the app shall test an arbitrary geocoding operation (eg: get the coordinates of the address of the Python Foundation) and if it fails it will raise an `ImproperlyConfigured` exception if ``DJANGO_LOCI_STRICT_GEOCODE_TEST`` is `True` or it will log an error otherwise (using the python logging facility).

Since this app does not use django-rest-framework, the geocoding operations should be performed via a [simple JSON view API that it is added to the admin as we do in django-netjsonconfig](https://github.com/openwisp/django-netjsonconfig/blob/3d14334391f99e964b85826fe085ea0b8a99b6e6/django_netjsonconfig/base/admin.py#L84-L98) (see `context_view` as a reference), although the logic to perform the geocoding can be stored in a function or a class to improve reusability.

This feature needs to be documented in the README and good tests must be written for it.

### PR DESCRIPTION
**Pull request by NoumbissiValere**
- Fixed regression tests which were failing
on openwisp_controller because of poorly
setup url

- Made map's urls dynamic

Closes #44

### CODE REVIEW

File: django_loci/static/django-loci/js/loci.js [hunk 1]
```diff
@@ -508,6 +518,14 @@ django.jQuery(function ($) {
...
     });
 
+    var pathname = window.location.pathname;
+    if (pathname.includes('django_loci') || pathname.includes('testdeviceapp')) {
+        $coordsUrl = getCoordsUrl('django_loci');
+        $addrUrl = getAddrUrl('django_loci');
+    } else if (pathname.includes('geo') || pathname.includes('device')) {
+        $coordsUrl = getCoordsUrl('geo');
+        $addrUrl = getAddrUrl('geo');
+    }
```
Comment (nemesisdesign) [inline django_loci/static/django-loci/js/loci.js:528]: Unfortunately this is not a good approach, because "geo" is from openwisp-controller, you're adding logic that knows details of openwisp-controller, violating the loose coupling principle.
It would also mean that any other app which extends this library and is not called "geo" will not work.

This issue was already addressed for the other URLs to get the floorplan data, there's an inline template override which generates the URL using the django view name, these are retrieved with javascript.
See:
- https://github.com/openwisp/django-loci/blob/master/django_loci/templates/admin/django_loci/location_inline.html
- https://github.com/openwisp/django-loci/blob/master/django_loci/static/django-loci/js/loci.js#L34-L35

You simply have to be consistent with what's already done, please keep this in mind for all subsequent pull requests.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
Almost there, but there's one issue regarding loose coupling.
See below.

The commit type is not a chore but fix (see the title I renamed).

**Comment by NoumbissiValere** [comment]
:smile: I knew it was a bad idea making `django_loci` aware of `geo`. It goes against the principle of orthogonality. Thanks @nemesisdesign I will fix this asap

**Review by nemesisdesign — APPROVED** [review]
It works! Thanks @NoumbissiValere :+1: :clap: 

I added a comment to the code, see 8f9ba43b455898fee5821ea4ea2fbaa25e57dd1f.
