### PR TITLE
[bug] Websocket connect error #63

### LINKED ISSUE #63: [bug] websocket connect error in location change form page
1. Create a location, set the marker and then check `is_mobile`.
2. Save the location.
3. Open it again and look at the console. (`Firefox can’t establish a connection to the server at ws://127.0.0.1:8000/ws/loci/location/undefined/.`)

### PR DESCRIPTION
**Pull request by atb00ker**
Closes #63

### CODE REVIEW

File: django_loci/static/django-loci/js/loci.js [hunk 1]
```diff
@@ -147,7 +147,7 @@ django.jQuery(function ($) {
             });
             // name not relevant in mobile locations
             $name.parents('.form-row').hide();
-            $('.no-location').show();
+            if (!$geometryTextarea.val()) { $('.no-location').show(); }
```
Comment (atb00ker) [inline django_loci/static/django-loci/js/loci.js:150]: If `$geometryTextarea.val()` has a value, it's not hidden. Hence, map and the message appear together, this condition will help avoid that.

File: django_loci/static/django-loci/js/loci.js [hunk 2]
```diff
@@ -371,14 +371,18 @@ django.jQuery(function ($) {
     }
 
     // show existing location
+    var pk;
     if ($location.val()) {
         $locationSelectionRow.hide();
         $geoEdit.show();
         isNew = false;
+        pk = $location.val();
```
Comment (atb00ker) [inline django_loci/static/django-loci/js/loci.js:379]: Changing `pk` value here should do the trick.
